spring.application.name=activityservice
server.port=8082
spring.mongodb.uri=mongodb+srv://Anubhavanand_fitness:Anubhav310@activityservice.kqyxop8.mongodb.net/ActivityMicroService?appName=activityService


